[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --alluredir=./reports/allure-results
markers =
    smoke: 冒烟测试用例
    regression: 回归测试用例